### ISSUE TITLE
Implement high-level comm protocol

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-RT#2]
What does this look like? Do we want to serialize ROS messages and send them over CAN? That seems heavyweight. I think a better idea is to develop a custom command set based on subsystem. 
Something along the lines of [4 bit command/status code][4 bit subsystem code] as ID, then command info in the message field. 

We can take inspiration from the current Jetson->Danfoss protocol, but that was designed a) for single motors and b) for unidirectional communication.

**Comment by JWCS** [comment]
Almost. Any system is built of layers, the current Jetson/Danfoss thing is exactly what you'll re-implement to begin with, because it is the building blocks for higher-level layers. 
(This is now reduplicated b/c I didn't realize there were multiple places)
The goal of a computer is to make a state+objective, after perceiving and reasoning about the world around it. Then it shares that idea (perhaps with context) to the controller. 
The controller implements the state+objective; it is a feedback control system. It does no computing, only controlling. It has different layers (hardware abstraction layer [hal], peripheral abstraction layer [pal], motion-groupings over individual members [subsystems], perhaps motion-groupings over subsystems [plans]), but it is driven by a direct knowledge of both target (already computed) and state (already computed/known/measured). 
But Jude, _what is the com spec_? What does it look like? It builds organically. 

- First you build the hal and pal layers (like the current Jetson/Danfoss have), sometimes directly on the computer - it's not computing much at first, like direct feed-through teleop.
  * Ergo it looks like the raw PWM/Canbus/Serial-Uart/Voltage-Current commands, but in digital quantities, used to control the controlled objects, transformed from a digital integer/float then into the final form (ex digital/serial int sent over serial to arduino converted into pwm).
- Then you end up grouping, naturally, things into subsystems on your computer; once the ideas of those are fleshed out, you move them to the better location for them, the controller. 
  * Instead of sending, say, serial integers of motor commands, after computing the desired values for the group on the computer, you just send the command for the group. It could still be quite simple: instead of sending the velocity for each lift motor, you send one for all of them. Instead of sending 4 wheel commands you send a velocity and rotation, or a differential velocity. 
  * It belongs on the controller because there is a desired target absolutely known, and a current state absolutely known, and what's left is to control the difference. 
- Then you start thinking of motion plans, like driving and digging, or driving and jerking and shaking the transport belt to get loose a stuck rock (I mean, if you had the time, why not?)
  * Since you have all the _only slightly_ lower-level tools/commands/interfaces made on the controller, this is trivial.
- Where does this stop? What does this message look like?
  * It stops when the amount of data being sent over the controller to do it's feedback control is significant; you wouldn't send raw lidar data, or raw camera data, but a (local) static/dynamic costmap _might_ still be fine (at DF we have all (all low-level hal/pal/subsystem control) of this done, and the controllers are super easy/beefy, so we would do path-planning and maybe cameras, depending on the design objective).
  * But for the thick lidars, stereo cameras, regular cameras even, if not super small res for particular job, those go to a computer vision-y computer, like the Jetson. 
  * Ok Jude, what does the message look like? Well, it doesn't really matter. Start with something simple, with room to grow it. In our case, canbus, you can use the id field to do a lot of level-abstraction encoding (targeting different layers with different ids, as you build them up). And if that becomes insufficient (for y'all it shouldn't), there is the J1949/canOpen standards, which are more feature dense. 
     * Trust me, it builds organicly, which is ok. The much bigger problem would be how are you communicating any big data. 
As for ROS msgs, if you pay close attention, you're really only sending a few things per message. Take (ideological) cues from that and the `formatter` class/package, if you're still wrapping your head around this. 
The biggest reason not to worry about this too much, more than getting higher level layers working on the computer, is that by the time you have this problem, everything else is already figured out, and all you have to do is implement it. You're not doing architecture or algorithm design, the implementation is 90% tuning parameters, not writing code.

**Comment by juliaschatz** [comment]
Spec for this has been laid out. Closing this ticket as the implementation needs to be done in each subsystem.
